name: NPM Check

on:
  pull_request:
    # Trigger on changes to the main branch, excluding dependabot updates
    # to avoid unnecessary workflow runs for automated dependency updates.
    branches:
      - main
      # Exclude branches created by Dependabot to prevent triggering the workflow
      - '!dependabot/**'
    paths:
      - npm/**
  workflow_dispatch:
  workflow_call:

jobs:
  npm-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: cd npm && npm install
      - name: Validate package
        run: cd npm && node -e "require('./index.js')"