name: Terraform Check

on:
  pull_request:
    branches:
      - main
    paths:
      - terraform/**
  workflow_dispatch:
  workflow_call:

jobs:
  terraform-validate:
    # exclude dependabot
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: cd terraform && terraform init -backend=false
      - name: Terraform Validate
        run: cd terraform && terraform validate