name: Terraform Check

on:
  pull_request:
    # Trigger on changes to the main branch, excluding dependabot updates
    # to avoid unnecessary workflow runs for automated dependency updates.
    branches:
      - main
      # Exclude branches created by Dependabot to prevent triggering the workflow
      - '!dependabot/**'
    paths:
      - terraform/**
  workflow_dispatch:
  workflow_call:

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: cd terraform && terraform init -backend=false
      - name: Terraform Validate
        run: cd terraform && terraform validate